<?xml version="1.0"?>
<package format="3">
  <name>sorting_cell_bringup</name>
  <version>1.0.0</version>
  <description>Launch files for the complete ROS 2 robot sorting workcell.</description>
  <maintainer email="1830051801@qq.com">Zhong Jiawei</maintainer>
  <license>MIT</license>
  <url type="repository">https://github.com/1830051801-ux/ros2-vision-guided-sorting-cell</url>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>controller_manager</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>ros_gz_bridge</exec_depend>
  <exec_depend>ros_gz_interfaces</exec_depend>
  <exec_depend>ros_gz_sim</exec_depend>
  <exec_depend>rosgraph_msgs</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>sorting_cell_core</exec_depend>
  <exec_depend>sorting_cell_description</exec_depend>
  <exec_depend>sorting_cell_gazebo</exec_depend>
  <exec_depend>xacro</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
